#!/usr/bin/env python3
from pathlib import Path
import json
import re
import sys

ROOT = Path(__file__).resolve().parent
errors = []


def read(rel):
    path = ROOT / rel
    if not path.exists():
        errors.append(f"Missing required Postman file: {rel}")
        return ""
    return path.read_text(encoding="utf-8")


def require(rel, *needles):
    text = read(rel)
    for needle in needles:
        if needle not in text:
            errors.append(f"{rel}: missing safety marker {needle!r}")
    return text


def forbid(rel, *needles):
    text = read(rel)
    for needle in needles:
        if needle in text:
            errors.append(f"{rel}: forbidden stale/unsafe value {needle!r}")
    return text


# Collection-level scripts run before request-level scripts, so they may validate URLs
# but must not reject dynamic body/header variables generated by a request pre-script.
collection_rel = "collections/Waypoint-Backend/.resources/definition.yaml"
require(
    collection_rel,
    "pm.request.headers.remove('X-Admin-TOTP')",
    "Unresolved Postman URL variables",
    "dynamic header/body variables",
    "/api/v1/auth/session/refresh",
    "waypointRefreshToken",
    "postman-auto-refresh",
    "pm.environment.set('previousWaypointRefreshToken', refreshToken)",
    "pm.environment.set('jwt', body.accessToken)",
    "pm.environment.set('waypointRefreshToken', body.refreshToken)",
    "pm.request.headers.upsert({ key: 'Authorization', value: `Bearer ${body.accessToken}` })",
)
forbid(
    collection_rel,
    "checkResolved('Body'",
    "checkResolved(`Header",
)

# Admin plan discovery is the source of truth for the running backend's configured variants.
plans_rel = "collections/Waypoint-Backend/05 - Admin/06 - Plans/01 - List Plans.request.yaml"
require(
    plans_rel,
    "providerVariantId",
    "pm.environment.set('monthlyVariantId', monthly.providerVariantId)",
    "pm.environment.set('annualVariantId', annual.providerVariantId)",
)

# Simulated webhook lifecycle tests must be repeatable, use the backend-synced variant,
# and remain independent of an expiring user JWT.
activate_rel = "collections/Waypoint-Backend/04 - Webhooks/01 - Subscription Events/01 - Activate Monthly Subscription.request.yaml"
activate = require(
    activate_rel,
    "Date.now()",
    "updated_at: now.toISOString()",
    "pm.environment.set('subscriptionId', subscriptionId)",
    "Run Admin > Plans > List Plans first",
    "/api/v1/admin/users/${expectedUserId}",
    "/api/v1/admin/subscriptions?userId=",
    "body.persistedPlan).to.eql('PREMIUM_MONTHLY')",
    "body.plan).to.eql('PREMIUM_MONTHLY')",
    "created.plan).to.eql('MONTHLY')",
    "created.status).to.eql('ACTIVE')",
)
forbid(activate_rel, "const jwt =", "A JWT for the same user is required", "/api/v1/subscriptions/current")

refund_rel = "collections/Waypoint-Backend/04 - Webhooks/01 - Subscription Events/02 - Refund Subscription.request.yaml"
refund = require(
    refund_rel,
    "updated_at: new Date().toISOString()",
    "Run Activate Monthly Subscription first",
    "/api/v1/admin/subscriptions?userId=",
    "refunded.status).to.eql('REFUNDED')",
)
forbid(refund_rel, "const jwt =", "A JWT for the same user is required", "/api/v1/subscriptions/current")
for text, name in [(activate, "activate monthly"), (refund, "refund")]:
    if "2030-01-01T00:00:00Z" in text:
        errors.append(f"{name}: hardcoded provider timestamp must not be used")

# Google manual/API login must be backend-controlled. Postman must never own the Google
# client secret, exchange provider authorization codes, or persist Google provider tokens.
google_start_rel = "collections/Waypoint-Backend/01 - Authentication/01 - Google/01 - Start Login.request.yaml"
google_complete_rel = "collections/Waypoint-Backend/01 - Authentication/01 - Google/02 - Complete Login.request.yaml"
require(
    google_start_rel,
    "/api/v1/auth/google/start",
    "body.authorizationUrl",
    "body.exchangeCode",
    "pm.environment.set('googleExchangeCode', body.exchangeCode)",
)
require(
    google_complete_rel,
    "/api/v1/auth/session/exchange",
    '"exchangeCode": "{{googleExchangeCode}}"',
    "body.refreshToken",
    "body.refreshExpiresIn",
    "pm.environment.set('waypointRefreshToken', body.refreshToken)",
)
for rel in [google_start_rel, google_complete_rel]:
    forbid(
        rel,
        "googleClientId",
        "googleClientSecret",
        "googleAccessToken",
        "googleRefreshToken",
        "oauth2.googleapis.com/token",
    )

# Current Subscription still detects malformed/stale credentials locally. Normally the
# collection pre-request script refreshes an expired Waypoint JWT before this script runs.
require(
    "collections/Waypoint-Backend/02 - Account and Entitlements/03 - Current Subscription.request.yaml",
    "payload.exp * 1000 <= Date.now()",
    "Waypoint JWT has expired",
    "waypointRefreshToken",
)

# User/admin selectors must clear dependent IDs before selecting new data.
require(
    "collections/Waypoint-Backend/05 - Admin/02 - Users/02 - Find User by Email.request.yaml",
    "pm.environment.unset('userId')",
    "pm.environment.unset('adminSubscriptionId')",
    "pm.environment.unset('adminGrantId')",
)
require(
    "collections/Waypoint-Backend/05 - Admin/03 - Subscriptions/01 - List Subscriptions.request.yaml",
    "pm.environment.unset('adminSubscriptionId')",
    "item.userId === expectedUserId",
)
require(
    "collections/Waypoint-Backend/05 - Admin/03 - Subscriptions/02 - Update Subscription.request.yaml",
    "subscriptionUserId !== userId",
    "Updated subscription still belongs to selected user",
)
require(
    "collections/Waypoint-Backend/05 - Admin/04 - Premium Special/03 - List Special Grants.request.yaml",
    "userId={{userId}}",
    "pm.environment.unset('adminGrantId')",
)
require(
    "collections/Waypoint-Backend/05 - Admin/05 - Webhook Events/01 - List Webhook Events.request.yaml",
    "pm.environment.unset('adminWebhookEventId')",
    "body.items.length === 1",
)

# Auth flows must not preserve credentials/IDs from a failed new login attempt.
for rel in [
    google_complete_rel,
    "collections/Waypoint-Backend/01 - Authentication/02 - Microsoft Login/02 - Exchange Session.request.yaml",
]:
    require(rel, "pm.environment.unset('jwt')", "pm.environment.unset('userId')")
require(
    "collections/Waypoint-Backend/01 - Authentication/03 - Session/02 - Logout.request.yaml",
    "pm.environment.unset('jwt')",
    "pm.environment.unset('userId')",
)

# Runtime-sensitive requests must not carry a stale fixed timestamp.
forbid(
    "collections/Waypoint-Backend/07 - AI/03 - Intent - Group Tabs.request.yaml",
    "2026-08-24T12:00:00+05:30",
)
require(
    "collections/Waypoint-Backend/07 - AI/03 - Intent - Group Tabs.request.yaml",
    "new Date().toISOString()",
)

# Lemon Squeezy lifecycle bootstrap must start clean.
require(
    "collections/Waypoint-Backend/06 - Lemon Squeezy Test Mode/01 - Setup/01 - Bootstrap Test Context.request.yaml",
    "lemonSqueezyLifecycleSubscriptionId",
    "lemonSqueezyInvoiceId",
    "pm.environment.unset(key)",
)

# Generated IDs and backend-derived billing variants must start empty in both environment representations.
yaml_env = read("environments/Waypoint Local.environment.yaml")
if re.search(r"- key: subscriptionId\s+value:\s*[^'\"\n]*postman-subscription", yaml_env):
    errors.append("Waypoint Local.environment.yaml: subscriptionId must start empty")
if "value: local-monthly-variant-id" in yaml_env:
    errors.append("Waypoint Local.environment.yaml: monthlyVariantId must come from Admin > Plans, not a fixed default")
for forbidden_google_key in [
    "googleClientId",
    "googleClientSecret",
    "googleOAuthRedirectUri",
    "googleAuthorizationCode",
    "googleRefreshToken",
    "googleAccessToken",
    "googleAccessTokenExpiresAt",
]:
    if f"- key: {forbidden_google_key}" in yaml_env:
        errors.append(f"Waypoint Local.environment.yaml: {forbidden_google_key} belongs to the backend/provider flow, not Postman")
for required_google_key in ["googleAuthorizationUrl", "googleExchangeCode"]:
    if f"- key: {required_google_key}" not in yaml_env:
        errors.append(f"Waypoint Local.environment.yaml: {required_google_key} is required for the backend-controlled Google flow")

json_env_path = ROOT / "Waypoint-Local.postman_environment.json"
try:
    env = json.loads(json_env_path.read_text(encoding="utf-8"))
    values = {item.get("key"): item.get("value") for item in env.get("values", [])}
    if values.get("subscriptionId"):
        errors.append("Waypoint-Local.postman_environment.json: subscriptionId must start empty")
    if values.get("monthlyVariantId"):
        errors.append("Waypoint-Local.postman_environment.json: monthlyVariantId must start empty and be populated from Admin > Plans")
    if values.get("annualVariantId"):
        errors.append("Waypoint-Local.postman_environment.json: annualVariantId must start empty and be populated from Admin > Plans")
    if "adminSubscriptionUserId" not in values:
        errors.append("Waypoint-Local.postman_environment.json: adminSubscriptionUserId is required")
    for forbidden_google_key in [
        "googleClientId",
        "googleClientSecret",
        "googleOAuthRedirectUri",
        "googleAuthorizationCode",
        "googleRefreshToken",
        "googleAccessToken",
        "googleAccessTokenExpiresAt",
    ]:
        if forbidden_google_key in values:
            errors.append(f"Waypoint-Local.postman_environment.json: {forbidden_google_key} belongs to the backend/provider flow, not Postman")
    for required_google_key in ["googleAuthorizationUrl", "googleExchangeCode"]:
        if required_google_key not in values:
            errors.append(f"Waypoint-Local.postman_environment.json: {required_google_key} is required for the backend-controlled Google flow")
except Exception as exc:
    errors.append(f"Waypoint-Local.postman_environment.json: invalid JSON: {exc}")

# Catch fixed IDs and provider-owned Google credentials/tokens anywhere in maintained Postman data files.
for path in ROOT.rglob("*"):
    if path.is_file() and path.suffix in {".yaml", ".json"}:
        text = path.read_text(encoding="utf-8")
        if "postman-subscription-001" in text:
            errors.append(f"{path.relative_to(ROOT)}: contains forbidden fixed subscription ID")
        for forbidden_google_marker in [
            "googleClientId",
            "googleClientSecret",
            "googleOAuthRedirectUri",
            "googleAuthorizationCode",
            "googleRefreshToken",
            "googleAccessToken",
            "googleAccessTokenExpiresAt",
            "oauth2.googleapis.com/token",
        ]:
            if forbidden_google_marker in text:
                errors.append(f"{path.relative_to(ROOT)}: contains provider-owned Google OAuth marker {forbidden_google_marker}")

if errors:
    print("Postman collection safety validation FAILED:")
    for error in errors:
        print(f" - {error}")
    sys.exit(1)

print("Postman collection safety validation passed.")
